CREATE TABLE invoices (
    invoice_id        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    file_name         VARCHAR2(500) NOT NULL,
    file_type         VARCHAR2(100),
    invoice_number    VARCHAR2(100),
    invoice_date      DATE,
    vendor_name       VARCHAR2(300),
    total_amount      NUMBER(18,2),
    taxable_amount    NUMBER(18,2),
    gstin             VARCHAR2(20),
    invoice_type      VARCHAR2(50),
    currency          VARCHAR2(10),
    uploaded_by       VARCHAR2(100),
    upload_date       TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    ocr_status        VARCHAR2(30) DEFAULT 'PENDING' NOT NULL,
    validation_status VARCHAR2(30) DEFAULT 'PENDING' NOT NULL,
    raw_text          CLOB,
    extracted_json    CLOB,
    created_at        TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at        TIMESTAMP
);

CREATE TABLE ocr_jobs (
    job_id            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_id        NUMBER NOT NULL,
    job_status        VARCHAR2(30) DEFAULT 'QUEUED' NOT NULL,
    input_file_name   VARCHAR2(500),
    output_json       CLOB,
    error_message     VARCHAR2(2000),
    started_at        TIMESTAMP,
    completed_at      TIMESTAMP,
    created_at        TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT fk_ocr_jobs_invoice
        FOREIGN KEY (invoice_id) REFERENCES invoices(invoice_id)
        ON DELETE CASCADE
);

CREATE INDEX idx_invoices_invoice_number ON invoices(invoice_number);
CREATE INDEX idx_invoices_vendor_name ON invoices(vendor_name);
CREATE INDEX idx_invoices_upload_date ON invoices(upload_date);
CREATE INDEX idx_ocr_jobs_invoice_id ON ocr_jobs(invoice_id);
